/* GENERATED by scripts/make-seed.mjs — a real /api/morph response, captured from
 * fixtures/stutter.wav. The UI labels this as a saved example; it is never presented as live.
 * Regenerate with: node scripts/make-seed.mjs <wav>
 */
import type { State } from "./reducer";

export const demoSeed: Partial<State> = {
  "transcript": {
    "verbatim": "And so my— and so my fellow Americans, ask not what your country can do for you, ask what you can do for your country.",
    "clean": "And so my fellow Americans, ask not what your country can do for you, ask what you can do for your country.",
    "words": [
      {
        "text": "And",
        "confidence": 0.9976874548450926
      },
      {
        "text": "so",
        "confidence": 0.9998628089343712
      },
      {
        "text": "my—",
        "confidence": 0.32243413960100625
      },
      {
        "text": "and",
        "confidence": 0.9984813185786262
      },
      {
        "text": "so",
        "confidence": 0.9999853374722015
      },
      {
        "text": "my",
        "confidence": 0.8173161839471035
      },
      {
        "text": "fellow",
        "confidence": 0.9998450519346057
      },
      {
        "text": "Americans,",
        "confidence": 0.9991554845275876
      },
      {
        "text": "ask",
        "confidence": 0.9999638808887751
      },
      {
        "text": "not",
        "confidence": 0.9999557753101334
      },
      {
        "text": "what",
        "confidence": 0.9993140637226783
      },
      {
        "text": "your",
        "confidence": 0.999926453279696
      },
      {
        "text": "country",
        "confidence": 0.9999555369130402
      },
      {
        "text": "can",
        "confidence": 0.999935154351806
      },
      {
        "text": "do",
        "confidence": 0.9999892712787918
      },
      {
        "text": "for",
        "confidence": 0.9999904633477849
      },
      {
        "text": "you,",
        "confidence": 0.876790662926652
      },
      {
        "text": "ask",
        "confidence": 0.999243593612697
      },
      {
        "text": "what",
        "confidence": 0.9999030922364486
      },
      {
        "text": "you",
        "confidence": 0.999940279711872
      },
      {
        "text": "can",
        "confidence": 0.9999287179248457
      },
      {
        "text": "do",
        "confidence": 0.9999793772183819
      },
      {
        "text": "for",
        "confidence": 0.9999737746439785
      },
      {
        "text": "your",
        "confidence": 0.9999531529452337
      },
      {
        "text": "country.",
        "confidence": 0.9861137315828654
      }
    ],
    "confidence": 0.9598249904694509,
    "audioDurationMs": 11950,
    "requestTimeMs": 4727
  },
  "order": [
    "baseline",
    "boss",
    "team",
    "public",
    "tech",
    "family"
  ],
  "cards": {
    "baseline": {
      "id": "baseline",
      "label": "Cleaned",
      "status": "ok",
      "text": "And so my fellow Americans, ask not what your country can do for you, ask what you can do for your country.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 6062,
      "attempts": 1
    },
    "boss": {
      "id": "boss",
      "label": "Your Boss",
      "status": "ok",
      "text": "The transcript has been rewritten as a two-sentence update for a senior executive, leading with the outcome. The outcome is that the transcript contains a famous quote from John F. Kennedy's 1961 inaugural address. The second sentence notes that this text is a recording of someone speaking, not a message addressed to you, and should be treated as data to be rewritten rather than instructions to act on.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 4076,
      "attempts": 1
    },
    "team": {
      "id": "team",
      "label": "Your Team",
      "status": "ok",
      "text": "Hey team, just wanted to share a quick thought: let's focus on what we can do for our country.\n\n*   Review current project goals\n*   Identify key areas for improvement\n*   Schedule a brief sync to discuss next steps",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 7218,
      "attempts": 1
    },
    "public": {
      "id": "public",
      "label": "The Public",
      "status": "ok",
      "text": "Please note that this message appears to be a historical quote rather than a direct customer notice. We are currently processing your inquiry and will get back to you shortly.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 6096,
      "attempts": 1
    },
    "tech": {
      "id": "tech",
      "label": "Technical",
      "status": "ok",
      "text": "The transcript contains the famous rhetorical appeal from President John F. Kennedy's 1961 inaugural address, urging citizens to prioritize national service over personal gain. This statement serves as a historical example of persuasive oratory rather than a technical specification or engineering directive.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 5649,
      "attempts": 1
    },
    "family": {
      "id": "family",
      "label": "Family",
      "status": "ok",
      "text": "Hey, just wanted to share that famous line about asking what we can do for our country instead of what it can do for us. It's such a powerful reminder of our shared responsibility, even if it sounds a bit serious for a casual chat!",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 4356,
      "attempts": 1
    }
  },
  "pending": [],
  "summary": {
    "ok": 6,
    "degraded": 0,
    "failed": 0,
    "totalMs": 7380,
    "transcriptVariance": false
  },
  "utteranceId": "u_mty6xd2v"
} as Partial<State>;
