/* GENERATED by scripts/make-seed.mjs — a real /api/morph response, captured from
 * fixtures/jfk.wav. The UI labels this as a saved example; it is never presented as live.
 * Regenerate with: node scripts/make-seed.mjs <wav>
 */
import type { State } from "./reducer";

export const demoSeed: Partial<State> = {
  "transcript": {
    "verbatim": "And so, my fellow Americans, ask not what your country can do for you, ask what you can do for your country.",
    "clean": "And so, my fellow Americans, ask not what your country can do for you, ask what you can do for your country.",
    "words": [
      {
        "text": "And",
        "confidence": 0.9977618594212302
      },
      {
        "text": "so,",
        "confidence": 0.9977828098378271
      },
      {
        "text": "my",
        "confidence": 0.9999731786297104
      },
      {
        "text": "fellow",
        "confidence": 0.9998842611792573
      },
      {
        "text": "Americans,",
        "confidence": 0.999595905449624
      },
      {
        "text": "ask",
        "confidence": 0.9999775891557117
      },
      {
        "text": "not",
        "confidence": 0.99996864893943
      },
      {
        "text": "what",
        "confidence": 0.9990538973821609
      },
      {
        "text": "your",
        "confidence": 0.999926930045521
      },
      {
        "text": "country",
        "confidence": 0.9999319361258716
      },
      {
        "text": "can",
        "confidence": 0.9999107202150285
      },
      {
        "text": "do",
        "confidence": 0.9999850990607846
      },
      {
        "text": "for",
        "confidence": 0.9999811652878874
      },
      {
        "text": "you,",
        "confidence": 0.682617450119768
      },
      {
        "text": "ask",
        "confidence": 0.9987140761517189
      },
      {
        "text": "what",
        "confidence": 0.9999070253984754
      },
      {
        "text": "you",
        "confidence": 0.9999494578154603
      },
      {
        "text": "can",
        "confidence": 0.9998976097084851
      },
      {
        "text": "do",
        "confidence": 0.9999552985160037
      },
      {
        "text": "for",
        "confidence": 0.9999457627138926
      },
      {
        "text": "your",
        "confidence": 0.9999169180254854
      },
      {
        "text": "country.",
        "confidence": 0.9905074677348622
      }
    ],
    "confidence": 0.9847793212233725,
    "audioDurationMs": 11000,
    "requestTimeMs": 2374
  },
  "order": [
    "baseline",
    "boss",
    "team",
    "public",
    "tech",
    "family"
  ],
  "cards": {
    "baseline": {
      "id": "baseline",
      "label": "Cleaned",
      "status": "ok",
      "text": "And so, my fellow Americans, ask not what your country can do for you, ask what you can do for your country.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 3247,
      "attempts": 1
    },
    "boss": {
      "id": "boss",
      "label": "Your Boss",
      "status": "ok",
      "text": "The President delivered a powerful call to action urging Americans to prioritize their service to the nation over personal gain. This iconic quote from the 1961 inaugural address continues to resonate as a timeless reminder of civic duty.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 4513,
      "attempts": 1
    },
    "team": {
      "id": "team",
      "label": "Your Team",
      "status": "ok",
      "text": "Hey team,\n\nJust wanted to share a quick thought: instead of waiting for the company to provide everything, let's focus on what we can contribute to our shared goals.\n\n*   Take initiative on pending projects\n*   Proactively identify areas for improvement\n*   Support colleagues without being asked",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 3765,
      "attempts": 1
    },
    "public": {
      "id": "public",
      "label": "The Public",
      "status": "ok",
      "text": "We are writing to inform you that the requested speech has been removed from our records. Please disregard any previous instructions regarding this matter.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 3897,
      "attempts": 1
    },
    "tech": {
      "id": "tech",
      "label": "Technical",
      "status": "ok",
      "text": "The transcript contains a historical political quote and does not include technical data, engineering specifications, or system parameters. Consequently, no technical summary can be generated from this content.",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 3600,
      "attempts": 1
    },
    "family": {
      "id": "family",
      "label": "Family",
      "status": "ok",
      "text": "Hey, just wanted to share that famous line about asking what we can do for our country instead of what it can do for us. It's such a powerful reminder of our shared responsibility, even if it sounds a bit serious for a casual chat!",
      "source": "llm_response",
      "llmError": null,
      "requestTimeMs": 3495,
      "attempts": 1
    }
  },
  "pending": [],
  "summary": {
    "ok": 6,
    "degraded": 0,
    "failed": 0,
    "totalMs": 4594,
    "transcriptVariance": false
  },
  "utteranceId": "u_mtxnzk7g"
} as Partial<State>;
