#!/usr/bin/env node
/**
 * Captures a real /api/morph response and writes it to src/state/demoSeed.ts so the
 * page is never empty on first load. The UI labels this as a saved example.
 *
 *   node scripts/make-seed.mjs [wav] [baseUrl]
 */
import { readFileSync, writeFileSync } from "node:fs";

const wav = process.argv[2] ?? "fixtures/jfk.wav";
const base = process.argv[3] ?? "http://localhost:3100";
const audio = readFileSync(wav);

const res = await fetch(`${base}/api/morph?lang=en&stream=0`, {
  method: "POST",
  headers: { "Content-Type": "audio/wav" },
  body: audio,
  signal: AbortSignal.timeout(120_000),
});
if (!res.ok) { console.error("morph failed", res.status, await res.text()); process.exit(1); }
const json = await res.json();

const ok = json.cards.filter((c) => c.status === "ok").length;
console.log(`captured ${json.cards.length} cards (${ok} ok) in ${json.summary.totalMs}ms from ${wav}`);
if (!json.transcript) { console.error("no transcript in response"); process.exit(1); }

const seed = {
  transcript: json.transcript,
  order: json.cards.map((c) => c.id),
  cards: Object.fromEntries(json.cards.map((c) => [c.id, c])),
  pending: [],
  summary: json.summary,
  utteranceId: json.utteranceId,
};

writeFileSync(
  "src/state/demoSeed.ts",
  `/* GENERATED by scripts/make-seed.mjs — a real /api/morph response, captured from
 * ${wav}. The UI labels this as a saved example; it is never presented as live.
 * Regenerate with: node scripts/make-seed.mjs <wav>
 */
import type { State } from "./reducer";

export const demoSeed: Partial<State> = ${JSON.stringify(seed, null, 2)} as Partial<State>;
`
);
console.log("wrote src/state/demoSeed.ts");
